#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_IMPORT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="coeco")]
	public partial class AncienneBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Inserttblclient(tblclient instance);
    partial void Updatetblclient(tblclient instance);
    partial void Deletetblclient(tblclient instance);
    partial void Inserttbluser(tbluser instance);
    partial void Updatetbluser(tbluser instance);
    partial void Deletetbluser(tbluser instance);
    partial void Inserttblemploye(tblemploye instance);
    partial void Updatetblemploye(tblemploye instance);
    partial void Deletetblemploye(tblemploye instance);
    partial void Inserttblheure(tblheure instance);
    partial void Updatetblheure(tblheure instance);
    partial void Deletetblheure(tblheure instance);
    partial void Inserttblprojet(tblprojet instance);
    partial void Updatetblprojet(tblprojet instance);
    partial void Deletetblprojet(tblprojet instance);
    partial void Inserttblprojetcat(tblprojetcat instance);
    partial void Updatetblprojetcat(tblprojetcat instance);
    partial void Deletetblprojetcat(tblprojetcat instance);
    partial void Inserttblprojetcatperso(tblprojetcatperso instance);
    partial void Updatetblprojetcatperso(tblprojetcatperso instance);
    partial void Deletetblprojetcatperso(tblprojetcatperso instance);
    partial void Inserttblprojetclient(tblprojetclient instance);
    partial void Updatetblprojetclient(tblprojetclient instance);
    partial void Deletetblprojetclient(tblprojetclient instance);
    partial void Inserttblresponsable(tblresponsable instance);
    partial void Updatetblresponsable(tblresponsable instance);
    partial void Deletetblresponsable(tblresponsable instance);
    partial void Inserttblstatut(tblstatut instance);
    partial void Updatetblstatut(tblstatut instance);
    partial void Deletetblstatut(tblstatut instance);
    #endregion
		
		public AncienneBDDataContext() : 
				base(global::BD_IMPORT.Properties.Settings.Default.coecoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AncienneBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AncienneBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AncienneBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AncienneBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblclient> tblclient
		{
			get
			{
				return this.GetTable<tblclient>();
			}
		}
		
		public System.Data.Linq.Table<tbluser> tbluser
		{
			get
			{
				return this.GetTable<tbluser>();
			}
		}
		
		public System.Data.Linq.Table<tblemploye> tblemploye
		{
			get
			{
				return this.GetTable<tblemploye>();
			}
		}
		
		public System.Data.Linq.Table<tblheure> tblheure
		{
			get
			{
				return this.GetTable<tblheure>();
			}
		}
		
		public System.Data.Linq.Table<tblprojet> tblprojet
		{
			get
			{
				return this.GetTable<tblprojet>();
			}
		}
		
		public System.Data.Linq.Table<tblprojetcat> tblprojetcat
		{
			get
			{
				return this.GetTable<tblprojetcat>();
			}
		}
		
		public System.Data.Linq.Table<tblprojetcatperso> tblprojetcatperso
		{
			get
			{
				return this.GetTable<tblprojetcatperso>();
			}
		}
		
		public System.Data.Linq.Table<tblprojetclient> tblprojetclient
		{
			get
			{
				return this.GetTable<tblprojetclient>();
			}
		}
		
		public System.Data.Linq.Table<tblresponsable> tblresponsable
		{
			get
			{
				return this.GetTable<tblresponsable>();
			}
		}
		
		public System.Data.Linq.Table<tblstatut> tblstatut
		{
			get
			{
				return this.GetTable<tblstatut>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblclient")]
	public partial class tblclient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _compagnie;
		
		private string _contact;
		
		private string _adresse;
		
		private string _ville;
		
		private string _province;
		
		private string _cp;
		
		private string _pays;
		
		private string _tel1;
		
		private string _tel1com;
		
		private string _tel2;
		
		private string _tel2com;
		
		private string _fax;
		
		private string _email;
		
		private string _siteweb;
		
		private System.DateTime _dateInsc;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncompagnieChanging(string value);
    partial void OncompagnieChanged();
    partial void OncontactChanging(string value);
    partial void OncontactChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OnvilleChanging(string value);
    partial void OnvilleChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncpChanging(string value);
    partial void OncpChanged();
    partial void OnpaysChanging(string value);
    partial void OnpaysChanged();
    partial void Ontel1Changing(string value);
    partial void Ontel1Changed();
    partial void Ontel1comChanging(string value);
    partial void Ontel1comChanged();
    partial void Ontel2Changing(string value);
    partial void Ontel2Changed();
    partial void Ontel2comChanging(string value);
    partial void Ontel2comChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsitewebChanging(string value);
    partial void OnsitewebChanged();
    partial void OndateInscChanging(System.DateTime value);
    partial void OndateInscChanged();
    #endregion
		
		public tblclient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compagnie", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string compagnie
		{
			get
			{
				return this._compagnie;
			}
			set
			{
				if ((this._compagnie != value))
				{
					this.OncompagnieChanging(value);
					this.SendPropertyChanging();
					this._compagnie = value;
					this.SendPropertyChanged("compagnie");
					this.OncompagnieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string contact
		{
			get
			{
				return this._contact;
			}
			set
			{
				if ((this._contact != value))
				{
					this.OncontactChanging(value);
					this.SendPropertyChanging();
					this._contact = value;
					this.SendPropertyChanged("contact");
					this.OncontactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ville
		{
			get
			{
				return this._ville;
			}
			set
			{
				if ((this._ville != value))
				{
					this.OnvilleChanging(value);
					this.SendPropertyChanging();
					this._ville = value;
					this.SendPropertyChanged("ville");
					this.OnvilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cp", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string cp
		{
			get
			{
				return this._cp;
			}
			set
			{
				if ((this._cp != value))
				{
					this.OncpChanging(value);
					this.SendPropertyChanging();
					this._cp = value;
					this.SendPropertyChanged("cp");
					this.OncpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pays", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string pays
		{
			get
			{
				return this._pays;
			}
			set
			{
				if ((this._pays != value))
				{
					this.OnpaysChanging(value);
					this.SendPropertyChanging();
					this._pays = value;
					this.SendPropertyChanged("pays");
					this.OnpaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel1
		{
			get
			{
				return this._tel1;
			}
			set
			{
				if ((this._tel1 != value))
				{
					this.Ontel1Changing(value);
					this.SendPropertyChanging();
					this._tel1 = value;
					this.SendPropertyChanged("tel1");
					this.Ontel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1com", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel1com
		{
			get
			{
				return this._tel1com;
			}
			set
			{
				if ((this._tel1com != value))
				{
					this.Ontel1comChanging(value);
					this.SendPropertyChanging();
					this._tel1com = value;
					this.SendPropertyChanged("tel1com");
					this.Ontel1comChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this.Ontel2Changing(value);
					this.SendPropertyChanging();
					this._tel2 = value;
					this.SendPropertyChanged("tel2");
					this.Ontel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2com", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel2com
		{
			get
			{
				return this._tel2com;
			}
			set
			{
				if ((this._tel2com != value))
				{
					this.Ontel2comChanging(value);
					this.SendPropertyChanging();
					this._tel2com = value;
					this.SendPropertyChanged("tel2com");
					this.Ontel2comChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteweb", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string siteweb
		{
			get
			{
				return this._siteweb;
			}
			set
			{
				if ((this._siteweb != value))
				{
					this.OnsitewebChanging(value);
					this.SendPropertyChanging();
					this._siteweb = value;
					this.SendPropertyChanged("siteweb");
					this.OnsitewebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsc", DbType="DateTime NOT NULL")]
		public System.DateTime dateInsc
		{
			get
			{
				return this._dateInsc;
			}
			set
			{
				if ((this._dateInsc != value))
				{
					this.OndateInscChanging(value);
					this.SendPropertyChanging();
					this._dateInsc = value;
					this.SendPropertyChanged("dateInsc");
					this.OndateInscChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbluser")]
	public partial class tbluser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _usr;
		
		private string _pwd;
		
		private string _prenom;
		
		private string _nom;
		
		private string _tpe;
		
		private int _idperso;
		
		private int _sttus;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusrChanging(string value);
    partial void OnusrChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OntpeChanging(string value);
    partial void OntpeChanged();
    partial void OnidpersoChanging(int value);
    partial void OnidpersoChanged();
    partial void OnsttusChanging(int value);
    partial void OnsttusChanged();
    #endregion
		
		public tbluser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string usr
		{
			get
			{
				return this._usr;
			}
			set
			{
				if ((this._usr != value))
				{
					this.OnusrChanging(value);
					this.SendPropertyChanging();
					this._usr = value;
					this.SendPropertyChanged("usr");
					this.OnusrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tpe", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string tpe
		{
			get
			{
				return this._tpe;
			}
			set
			{
				if ((this._tpe != value))
				{
					this.OntpeChanging(value);
					this.SendPropertyChanging();
					this._tpe = value;
					this.SendPropertyChanged("tpe");
					this.OntpeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idperso", DbType="Int NOT NULL")]
		public int idperso
		{
			get
			{
				return this._idperso;
			}
			set
			{
				if ((this._idperso != value))
				{
					this.OnidpersoChanging(value);
					this.SendPropertyChanging();
					this._idperso = value;
					this.SendPropertyChanged("idperso");
					this.OnidpersoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sttus", DbType="Int NOT NULL")]
		public int sttus
		{
			get
			{
				return this._sttus;
			}
			set
			{
				if ((this._sttus != value))
				{
					this.OnsttusChanging(value);
					this.SendPropertyChanging();
					this._sttus = value;
					this.SendPropertyChanged("sttus");
					this.OnsttusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblemploye")]
	public partial class tblemploye : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nom;
		
		private string _prenom;
		
		private string _adresse;
		
		private string _ville;
		
		private string _province;
		
		private string _cp;
		
		private string _pays;
		
		private string _tel1;
		
		private string _tel1com;
		
		private string _tel2;
		
		private string _tel2com;
		
		private string _fax;
		
		private string _email;
		
		private double _salaireheure;
		
		private System.DateTime _dateInsc;
		
		private int _status;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OnvilleChanging(string value);
    partial void OnvilleChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncpChanging(string value);
    partial void OncpChanged();
    partial void OnpaysChanging(string value);
    partial void OnpaysChanged();
    partial void Ontel1Changing(string value);
    partial void Ontel1Changed();
    partial void Ontel1comChanging(string value);
    partial void Ontel1comChanged();
    partial void Ontel2Changing(string value);
    partial void Ontel2Changed();
    partial void Ontel2comChanging(string value);
    partial void Ontel2comChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsalaireheureChanging(double value);
    partial void OnsalaireheureChanged();
    partial void OndateInscChanging(System.DateTime value);
    partial void OndateInscChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    #endregion
		
		public tblemploye()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ville
		{
			get
			{
				return this._ville;
			}
			set
			{
				if ((this._ville != value))
				{
					this.OnvilleChanging(value);
					this.SendPropertyChanging();
					this._ville = value;
					this.SendPropertyChanged("ville");
					this.OnvilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cp", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string cp
		{
			get
			{
				return this._cp;
			}
			set
			{
				if ((this._cp != value))
				{
					this.OncpChanging(value);
					this.SendPropertyChanging();
					this._cp = value;
					this.SendPropertyChanged("cp");
					this.OncpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pays", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string pays
		{
			get
			{
				return this._pays;
			}
			set
			{
				if ((this._pays != value))
				{
					this.OnpaysChanging(value);
					this.SendPropertyChanging();
					this._pays = value;
					this.SendPropertyChanged("pays");
					this.OnpaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel1
		{
			get
			{
				return this._tel1;
			}
			set
			{
				if ((this._tel1 != value))
				{
					this.Ontel1Changing(value);
					this.SendPropertyChanging();
					this._tel1 = value;
					this.SendPropertyChanged("tel1");
					this.Ontel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1com", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel1com
		{
			get
			{
				return this._tel1com;
			}
			set
			{
				if ((this._tel1com != value))
				{
					this.Ontel1comChanging(value);
					this.SendPropertyChanging();
					this._tel1com = value;
					this.SendPropertyChanged("tel1com");
					this.Ontel1comChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this.Ontel2Changing(value);
					this.SendPropertyChanging();
					this._tel2 = value;
					this.SendPropertyChanged("tel2");
					this.Ontel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2com", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel2com
		{
			get
			{
				return this._tel2com;
			}
			set
			{
				if ((this._tel2com != value))
				{
					this.Ontel2comChanging(value);
					this.SendPropertyChanging();
					this._tel2com = value;
					this.SendPropertyChanged("tel2com");
					this.Ontel2comChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaireheure", DbType="Float NOT NULL")]
		public double salaireheure
		{
			get
			{
				return this._salaireheure;
			}
			set
			{
				if ((this._salaireheure != value))
				{
					this.OnsalaireheureChanging(value);
					this.SendPropertyChanging();
					this._salaireheure = value;
					this.SendPropertyChanged("salaireheure");
					this.OnsalaireheureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsc", DbType="DateTime NOT NULL")]
		public System.DateTime dateInsc
		{
			get
			{
				return this._dateInsc;
			}
			set
			{
				if ((this._dateInsc != value))
				{
					this.OndateInscChanging(value);
					this.SendPropertyChanging();
					this._dateInsc = value;
					this.SendPropertyChanged("dateInsc");
					this.OndateInscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblheure")]
	public partial class tblheure : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idprojet;
		
		private int _idcat;
		
		private int _idperso;
		
		private string _tbl;
		
		private System.Nullable<System.DateTime> _dateEffect;
		
		private double _temps;
		
		private string _note;
		
		private System.DateTime _dateInsc;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidprojetChanging(int value);
    partial void OnidprojetChanged();
    partial void OnidcatChanging(int value);
    partial void OnidcatChanged();
    partial void OnidpersoChanging(int value);
    partial void OnidpersoChanged();
    partial void OntblChanging(string value);
    partial void OntblChanged();
    partial void OndateEffectChanging(System.Nullable<System.DateTime> value);
    partial void OndateEffectChanged();
    partial void OntempsChanging(double value);
    partial void OntempsChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OndateInscChanging(System.DateTime value);
    partial void OndateInscChanged();
    #endregion
		
		public tblheure()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idprojet", DbType="Int NOT NULL")]
		public int idprojet
		{
			get
			{
				return this._idprojet;
			}
			set
			{
				if ((this._idprojet != value))
				{
					this.OnidprojetChanging(value);
					this.SendPropertyChanging();
					this._idprojet = value;
					this.SendPropertyChanged("idprojet");
					this.OnidprojetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcat", DbType="Int NOT NULL")]
		public int idcat
		{
			get
			{
				return this._idcat;
			}
			set
			{
				if ((this._idcat != value))
				{
					this.OnidcatChanging(value);
					this.SendPropertyChanging();
					this._idcat = value;
					this.SendPropertyChanged("idcat");
					this.OnidcatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idperso", DbType="Int NOT NULL")]
		public int idperso
		{
			get
			{
				return this._idperso;
			}
			set
			{
				if ((this._idperso != value))
				{
					this.OnidpersoChanging(value);
					this.SendPropertyChanging();
					this._idperso = value;
					this.SendPropertyChanged("idperso");
					this.OnidpersoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string tbl
		{
			get
			{
				return this._tbl;
			}
			set
			{
				if ((this._tbl != value))
				{
					this.OntblChanging(value);
					this.SendPropertyChanging();
					this._tbl = value;
					this.SendPropertyChanged("tbl");
					this.OntblChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateEffect", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateEffect
		{
			get
			{
				return this._dateEffect;
			}
			set
			{
				if ((this._dateEffect != value))
				{
					this.OndateEffectChanging(value);
					this.SendPropertyChanging();
					this._dateEffect = value;
					this.SendPropertyChanged("dateEffect");
					this.OndateEffectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temps", DbType="Float NOT NULL")]
		public double temps
		{
			get
			{
				return this._temps;
			}
			set
			{
				if ((this._temps != value))
				{
					this.OntempsChanging(value);
					this.SendPropertyChanging();
					this._temps = value;
					this.SendPropertyChanged("temps");
					this.OntempsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsc", DbType="DateTime NOT NULL")]
		public System.DateTime dateInsc
		{
			get
			{
				return this._dateInsc;
			}
			set
			{
				if ((this._dateInsc != value))
				{
					this.OndateInscChanging(value);
					this.SendPropertyChanging();
					this._dateInsc = value;
					this.SendPropertyChanged("dateInsc");
					this.OndateInscChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblprojet")]
	public partial class tblprojet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _noprojet;
		
		private string _titre;
		
		private string _description;
		
		private int _idstatut;
		
		private int _idresponsable;
		
		private double _temps;
		
		private double _montantsalaire;
		
		private double _montantcontribnature;
		
		private double _montantcontribespece;
		
		private System.Nullable<System.DateTime> _datedebut;
		
		private System.Nullable<System.DateTime> _datefin;
		
		private System.Nullable<System.DateTime> _dateInsc;
		
		private int _status;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoprojetChanging(string value);
    partial void OnnoprojetChanged();
    partial void OntitreChanging(string value);
    partial void OntitreChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnidstatutChanging(int value);
    partial void OnidstatutChanged();
    partial void OnidresponsableChanging(int value);
    partial void OnidresponsableChanged();
    partial void OntempsChanging(double value);
    partial void OntempsChanged();
    partial void OnmontantsalaireChanging(double value);
    partial void OnmontantsalaireChanged();
    partial void OnmontantcontribnatureChanging(double value);
    partial void OnmontantcontribnatureChanged();
    partial void OnmontantcontribespeceChanging(double value);
    partial void OnmontantcontribespeceChanged();
    partial void OndatedebutChanging(System.Nullable<System.DateTime> value);
    partial void OndatedebutChanged();
    partial void OndatefinChanging(System.Nullable<System.DateTime> value);
    partial void OndatefinChanged();
    partial void OndateInscChanging(System.Nullable<System.DateTime> value);
    partial void OndateInscChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    #endregion
		
		public tblprojet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noprojet", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string noprojet
		{
			get
			{
				return this._noprojet;
			}
			set
			{
				if ((this._noprojet != value))
				{
					this.OnnoprojetChanging(value);
					this.SendPropertyChanging();
					this._noprojet = value;
					this.SendPropertyChanged("noprojet");
					this.OnnoprojetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titre", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string titre
		{
			get
			{
				return this._titre;
			}
			set
			{
				if ((this._titre != value))
				{
					this.OntitreChanging(value);
					this.SendPropertyChanging();
					this._titre = value;
					this.SendPropertyChanged("titre");
					this.OntitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idstatut", DbType="Int NOT NULL")]
		public int idstatut
		{
			get
			{
				return this._idstatut;
			}
			set
			{
				if ((this._idstatut != value))
				{
					this.OnidstatutChanging(value);
					this.SendPropertyChanging();
					this._idstatut = value;
					this.SendPropertyChanged("idstatut");
					this.OnidstatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idresponsable", DbType="Int NOT NULL")]
		public int idresponsable
		{
			get
			{
				return this._idresponsable;
			}
			set
			{
				if ((this._idresponsable != value))
				{
					this.OnidresponsableChanging(value);
					this.SendPropertyChanging();
					this._idresponsable = value;
					this.SendPropertyChanged("idresponsable");
					this.OnidresponsableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temps", DbType="Float NOT NULL")]
		public double temps
		{
			get
			{
				return this._temps;
			}
			set
			{
				if ((this._temps != value))
				{
					this.OntempsChanging(value);
					this.SendPropertyChanging();
					this._temps = value;
					this.SendPropertyChanged("temps");
					this.OntempsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montantsalaire", DbType="Float NOT NULL")]
		public double montantsalaire
		{
			get
			{
				return this._montantsalaire;
			}
			set
			{
				if ((this._montantsalaire != value))
				{
					this.OnmontantsalaireChanging(value);
					this.SendPropertyChanging();
					this._montantsalaire = value;
					this.SendPropertyChanged("montantsalaire");
					this.OnmontantsalaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montantcontribnature", DbType="Float NOT NULL")]
		public double montantcontribnature
		{
			get
			{
				return this._montantcontribnature;
			}
			set
			{
				if ((this._montantcontribnature != value))
				{
					this.OnmontantcontribnatureChanging(value);
					this.SendPropertyChanging();
					this._montantcontribnature = value;
					this.SendPropertyChanged("montantcontribnature");
					this.OnmontantcontribnatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montantcontribespece", DbType="Float NOT NULL")]
		public double montantcontribespece
		{
			get
			{
				return this._montantcontribespece;
			}
			set
			{
				if ((this._montantcontribespece != value))
				{
					this.OnmontantcontribespeceChanging(value);
					this.SendPropertyChanging();
					this._montantcontribespece = value;
					this.SendPropertyChanged("montantcontribespece");
					this.OnmontantcontribespeceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datedebut", DbType="Date")]
		public System.Nullable<System.DateTime> datedebut
		{
			get
			{
				return this._datedebut;
			}
			set
			{
				if ((this._datedebut != value))
				{
					this.OndatedebutChanging(value);
					this.SendPropertyChanging();
					this._datedebut = value;
					this.SendPropertyChanged("datedebut");
					this.OndatedebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datefin", DbType="Date")]
		public System.Nullable<System.DateTime> datefin
		{
			get
			{
				return this._datefin;
			}
			set
			{
				if ((this._datefin != value))
				{
					this.OndatefinChanging(value);
					this.SendPropertyChanging();
					this._datefin = value;
					this.SendPropertyChanged("datefin");
					this.OndatefinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsc", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateInsc
		{
			get
			{
				return this._dateInsc;
			}
			set
			{
				if ((this._dateInsc != value))
				{
					this.OndateInscChanging(value);
					this.SendPropertyChanging();
					this._dateInsc = value;
					this.SendPropertyChanged("dateInsc");
					this.OndateInscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblprojetcat")]
	public partial class tblprojetcat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idprojet;
		
		private int _idcatmaitre;
		
		private string _titre;
		
		private string _description;
		
		private double _temps;
		
		private double _montantsalaire;
		
		private double _montantcontribnature;
		
		private double _montantcontribespece;
		
		private int _niveau;
		
		private System.DateTime _dateInsc;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidprojetChanging(int value);
    partial void OnidprojetChanged();
    partial void OnidcatmaitreChanging(int value);
    partial void OnidcatmaitreChanged();
    partial void OntitreChanging(string value);
    partial void OntitreChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OntempsChanging(double value);
    partial void OntempsChanged();
    partial void OnmontantsalaireChanging(double value);
    partial void OnmontantsalaireChanged();
    partial void OnmontantcontribnatureChanging(double value);
    partial void OnmontantcontribnatureChanged();
    partial void OnmontantcontribespeceChanging(double value);
    partial void OnmontantcontribespeceChanged();
    partial void OnniveauChanging(int value);
    partial void OnniveauChanged();
    partial void OndateInscChanging(System.DateTime value);
    partial void OndateInscChanged();
    #endregion
		
		public tblprojetcat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idprojet", DbType="Int NOT NULL")]
		public int idprojet
		{
			get
			{
				return this._idprojet;
			}
			set
			{
				if ((this._idprojet != value))
				{
					this.OnidprojetChanging(value);
					this.SendPropertyChanging();
					this._idprojet = value;
					this.SendPropertyChanged("idprojet");
					this.OnidprojetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcatmaitre", DbType="Int NOT NULL")]
		public int idcatmaitre
		{
			get
			{
				return this._idcatmaitre;
			}
			set
			{
				if ((this._idcatmaitre != value))
				{
					this.OnidcatmaitreChanging(value);
					this.SendPropertyChanging();
					this._idcatmaitre = value;
					this.SendPropertyChanged("idcatmaitre");
					this.OnidcatmaitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titre", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string titre
		{
			get
			{
				return this._titre;
			}
			set
			{
				if ((this._titre != value))
				{
					this.OntitreChanging(value);
					this.SendPropertyChanging();
					this._titre = value;
					this.SendPropertyChanged("titre");
					this.OntitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temps", DbType="Float NOT NULL")]
		public double temps
		{
			get
			{
				return this._temps;
			}
			set
			{
				if ((this._temps != value))
				{
					this.OntempsChanging(value);
					this.SendPropertyChanging();
					this._temps = value;
					this.SendPropertyChanged("temps");
					this.OntempsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montantsalaire", DbType="Float NOT NULL")]
		public double montantsalaire
		{
			get
			{
				return this._montantsalaire;
			}
			set
			{
				if ((this._montantsalaire != value))
				{
					this.OnmontantsalaireChanging(value);
					this.SendPropertyChanging();
					this._montantsalaire = value;
					this.SendPropertyChanged("montantsalaire");
					this.OnmontantsalaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montantcontribnature", DbType="Float NOT NULL")]
		public double montantcontribnature
		{
			get
			{
				return this._montantcontribnature;
			}
			set
			{
				if ((this._montantcontribnature != value))
				{
					this.OnmontantcontribnatureChanging(value);
					this.SendPropertyChanging();
					this._montantcontribnature = value;
					this.SendPropertyChanged("montantcontribnature");
					this.OnmontantcontribnatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montantcontribespece", DbType="Float NOT NULL")]
		public double montantcontribespece
		{
			get
			{
				return this._montantcontribespece;
			}
			set
			{
				if ((this._montantcontribespece != value))
				{
					this.OnmontantcontribespeceChanging(value);
					this.SendPropertyChanging();
					this._montantcontribespece = value;
					this.SendPropertyChanged("montantcontribespece");
					this.OnmontantcontribespeceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau", DbType="Int NOT NULL")]
		public int niveau
		{
			get
			{
				return this._niveau;
			}
			set
			{
				if ((this._niveau != value))
				{
					this.OnniveauChanging(value);
					this.SendPropertyChanging();
					this._niveau = value;
					this.SendPropertyChanged("niveau");
					this.OnniveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsc", DbType="DateTime NOT NULL")]
		public System.DateTime dateInsc
		{
			get
			{
				return this._dateInsc;
			}
			set
			{
				if ((this._dateInsc != value))
				{
					this.OndateInscChanging(value);
					this.SendPropertyChanging();
					this._dateInsc = value;
					this.SendPropertyChanged("dateInsc");
					this.OndateInscChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblprojetcatperso")]
	public partial class tblprojetcatperso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idprojet;
		
		private int _idcat;
		
		private int _idperso;
		
		private string _tbl;
		
		private double _nbrheure;
		
		private System.DateTime _dateInsc;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidprojetChanging(int value);
    partial void OnidprojetChanged();
    partial void OnidcatChanging(int value);
    partial void OnidcatChanged();
    partial void OnidpersoChanging(int value);
    partial void OnidpersoChanged();
    partial void OntblChanging(string value);
    partial void OntblChanged();
    partial void OnnbrheureChanging(double value);
    partial void OnnbrheureChanged();
    partial void OndateInscChanging(System.DateTime value);
    partial void OndateInscChanged();
    #endregion
		
		public tblprojetcatperso()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idprojet", DbType="Int NOT NULL")]
		public int idprojet
		{
			get
			{
				return this._idprojet;
			}
			set
			{
				if ((this._idprojet != value))
				{
					this.OnidprojetChanging(value);
					this.SendPropertyChanging();
					this._idprojet = value;
					this.SendPropertyChanged("idprojet");
					this.OnidprojetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcat", DbType="Int NOT NULL")]
		public int idcat
		{
			get
			{
				return this._idcat;
			}
			set
			{
				if ((this._idcat != value))
				{
					this.OnidcatChanging(value);
					this.SendPropertyChanging();
					this._idcat = value;
					this.SendPropertyChanged("idcat");
					this.OnidcatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idperso", DbType="Int NOT NULL")]
		public int idperso
		{
			get
			{
				return this._idperso;
			}
			set
			{
				if ((this._idperso != value))
				{
					this.OnidpersoChanging(value);
					this.SendPropertyChanging();
					this._idperso = value;
					this.SendPropertyChanged("idperso");
					this.OnidpersoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tbl
		{
			get
			{
				return this._tbl;
			}
			set
			{
				if ((this._tbl != value))
				{
					this.OntblChanging(value);
					this.SendPropertyChanging();
					this._tbl = value;
					this.SendPropertyChanged("tbl");
					this.OntblChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrheure", DbType="Float NOT NULL")]
		public double nbrheure
		{
			get
			{
				return this._nbrheure;
			}
			set
			{
				if ((this._nbrheure != value))
				{
					this.OnnbrheureChanging(value);
					this.SendPropertyChanging();
					this._nbrheure = value;
					this.SendPropertyChanged("nbrheure");
					this.OnnbrheureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsc", DbType="DateTime NOT NULL")]
		public System.DateTime dateInsc
		{
			get
			{
				return this._dateInsc;
			}
			set
			{
				if ((this._dateInsc != value))
				{
					this.OndateInscChanging(value);
					this.SendPropertyChanging();
					this._dateInsc = value;
					this.SendPropertyChanged("dateInsc");
					this.OndateInscChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblprojetclient")]
	public partial class tblprojetclient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idclient;
		
		private int _idprojet;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidclientChanging(int value);
    partial void OnidclientChanged();
    partial void OnidprojetChanging(int value);
    partial void OnidprojetChanged();
    #endregion
		
		public tblprojetclient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idclient", DbType="Int NOT NULL")]
		public int idclient
		{
			get
			{
				return this._idclient;
			}
			set
			{
				if ((this._idclient != value))
				{
					this.OnidclientChanging(value);
					this.SendPropertyChanging();
					this._idclient = value;
					this.SendPropertyChanged("idclient");
					this.OnidclientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idprojet", DbType="Int NOT NULL")]
		public int idprojet
		{
			get
			{
				return this._idprojet;
			}
			set
			{
				if ((this._idprojet != value))
				{
					this.OnidprojetChanging(value);
					this.SendPropertyChanging();
					this._idprojet = value;
					this.SendPropertyChanged("idprojet");
					this.OnidprojetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblresponsable")]
	public partial class tblresponsable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nom;
		
		private string _prenom;
		
		private string _adresse;
		
		private string _ville;
		
		private string _province;
		
		private string _cp;
		
		private string _pays;
		
		private string _tel1;
		
		private string _tel1com;
		
		private string _tel2;
		
		private string _tel2com;
		
		private string _fax;
		
		private string _email;
		
		private double _salaireheure;
		
		private System.DateTime _dateInsc;
		
		private int _status;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OnvilleChanging(string value);
    partial void OnvilleChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncpChanging(string value);
    partial void OncpChanged();
    partial void OnpaysChanging(string value);
    partial void OnpaysChanged();
    partial void Ontel1Changing(string value);
    partial void Ontel1Changed();
    partial void Ontel1comChanging(string value);
    partial void Ontel1comChanged();
    partial void Ontel2Changing(string value);
    partial void Ontel2Changed();
    partial void Ontel2comChanging(string value);
    partial void Ontel2comChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsalaireheureChanging(double value);
    partial void OnsalaireheureChanged();
    partial void OndateInscChanging(System.DateTime value);
    partial void OndateInscChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    #endregion
		
		public tblresponsable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ville
		{
			get
			{
				return this._ville;
			}
			set
			{
				if ((this._ville != value))
				{
					this.OnvilleChanging(value);
					this.SendPropertyChanging();
					this._ville = value;
					this.SendPropertyChanged("ville");
					this.OnvilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cp", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string cp
		{
			get
			{
				return this._cp;
			}
			set
			{
				if ((this._cp != value))
				{
					this.OncpChanging(value);
					this.SendPropertyChanging();
					this._cp = value;
					this.SendPropertyChanged("cp");
					this.OncpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pays", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string pays
		{
			get
			{
				return this._pays;
			}
			set
			{
				if ((this._pays != value))
				{
					this.OnpaysChanging(value);
					this.SendPropertyChanging();
					this._pays = value;
					this.SendPropertyChanged("pays");
					this.OnpaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel1
		{
			get
			{
				return this._tel1;
			}
			set
			{
				if ((this._tel1 != value))
				{
					this.Ontel1Changing(value);
					this.SendPropertyChanging();
					this._tel1 = value;
					this.SendPropertyChanged("tel1");
					this.Ontel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1com", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel1com
		{
			get
			{
				return this._tel1com;
			}
			set
			{
				if ((this._tel1com != value))
				{
					this.Ontel1comChanging(value);
					this.SendPropertyChanging();
					this._tel1com = value;
					this.SendPropertyChanged("tel1com");
					this.Ontel1comChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this.Ontel2Changing(value);
					this.SendPropertyChanging();
					this._tel2 = value;
					this.SendPropertyChanged("tel2");
					this.Ontel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2com", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tel2com
		{
			get
			{
				return this._tel2com;
			}
			set
			{
				if ((this._tel2com != value))
				{
					this.Ontel2comChanging(value);
					this.SendPropertyChanging();
					this._tel2com = value;
					this.SendPropertyChanged("tel2com");
					this.Ontel2comChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaireheure", DbType="Float NOT NULL")]
		public double salaireheure
		{
			get
			{
				return this._salaireheure;
			}
			set
			{
				if ((this._salaireheure != value))
				{
					this.OnsalaireheureChanging(value);
					this.SendPropertyChanging();
					this._salaireheure = value;
					this.SendPropertyChanged("salaireheure");
					this.OnsalaireheureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsc", DbType="DateTime NOT NULL")]
		public System.DateTime dateInsc
		{
			get
			{
				return this._dateInsc;
			}
			set
			{
				if ((this._dateInsc != value))
				{
					this.OndateInscChanging(value);
					this.SendPropertyChanging();
					this._dateInsc = value;
					this.SendPropertyChanged("dateInsc");
					this.OndateInscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblstatut")]
	public partial class tblstatut : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _titre;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitreChanging(string value);
    partial void OntitreChanged();
    #endregion
		
		public tblstatut()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titre", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string titre
		{
			get
			{
				return this._titre;
			}
			set
			{
				if ((this._titre != value))
				{
					this.OntitreChanging(value);
					this.SendPropertyChanging();
					this._titre = value;
					this.SendPropertyChanged("titre");
					this.OntitreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
