USE BD_Coeco_Test
GO

ALTER DATABASE BD_Coeco_Test
ADD FILEGROUP fsGroup CONTAINS FILESTREAM
GO

ALTER DATABASE BD_Coeco_Test
ADD FILE (
	NAME = 'fsBD_CoEco', FILENAME = 'C:\BD_CoEco'
) TO FILEGROUP fsGroup
GO

EXEC sp_configure filestream_access_level, 2
RECONFIGURE

CREATE TABLE tbl_Facture (
	idFacture INT IDENTITY(1,1),
	uniqueID UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE DEFAULT (newid()),
	facture VARBINARY(MAX) FILESTREAM NULL,

	CONSTRAINT pkIdFacture PRIMARY KEY (idFacture),
)

ALTER TABLE tbl_Depense
	ADD idFacture INTEGER NULL

ALTER TABLE tbl_Depense
	ADD CONSTRAINT fkIdFacture
	FOREIGN KEY (idFacture) REFERENCES tbl_Facture(idFacture)
	